version: '3'
services:
    nginx:
        image: 'okty/nginx:1.14'
        ports:
            - '8080:80'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - MAX_UPLOAD_SIZE=2M
            - PHP_CONTAINER_ID=php
            - INDEX_SUBFOLDER=public
    mysql:
        image: 'mysql:8'
        ports:
            - '3306:3306'
        volumes:
            - './docker/database:/var/lib/mysql'
        environment:
            - MYSQL_DATABASE=blog
            - MYSQL_USER=alex
            - MYSQL_PASSWORD=monFabuleuxMotDePasse
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    adminer:
        image: 'adminer:latest'
        ports:
            - '8081:8080'
    php:
        image: 'okty/php:7.2'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - PHP_EXTENSIONS=pdo_mysql
